server:
  port: 8089   #端口号
  servlet:
    context-path: /aip/v1
  tomcat:
    max-http-post-size: 300000MB
    connection-timeout: 180000000 #连接时间
spring:
  datasource:      #连接数据库配置
    url: jdbc:mysql://192.168.1.205:3306/edgeofcomputingai?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class- name: com.mysql.jdbc.Driver
  servlet:       #    文件上传配置  文件大小 MB必须大写
    multipart:
      enabled: true
      max-file-size: 300000MB   # maxFileSize 是单个文件大小
      max-request-size: 500000MB   # maxRequestSize是设置总上传的数据大小

#连接ceph
ceph:
  file:
    admin: UT8AMGN23LVOJBTNMYP6
    ip: http://192.168.1.37:7480
    key: 5q8hfDupnvA3KS1icyq8XMRqYfbXARCUkOO7bK0X
